version: '3'

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - node-network
    tty: true
    depends_on:
      - app

  app:
    build: 
      context: ./src
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ./src:/usr/src/app
    tty: true
    depends_on:
      - db 

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge